datastax/cdc-apache-cassandra

- producer-v3-pulsar/src/test/java/com/datastax/cassandra/cdc/producer/PulsarProducerV3Tests.java
- producer-v4-pulsar/src/test/java/com/datastax/cassandra/cdc/producer/PulsarProducerV4Tests.java
- source-pulsar/src/main/java/com/datastax/oss/pulsar/source/CassandraSource.java
- source-pulsar/src/test/java/com/datastax/oss/pulsar/source/PulsarCassandraSourceTests.java
Problem:
with `KeyValue<GenericRecord, MutationValue>` the consume needs to fetch the Schema and if the topic does not exist or it has no schema you will face an error (this is a bug in Pulsar actually)
Changes:
use Schema.AUTO_CONSUME() in order to deal with this problem, the AUTO_CONSUME schema downloads automatically and ondemand, as soon as it handles a message, so the topic may be non existant
> Use Consumer<GenericObject> in order to prevent errors if the topic is not present or without a schema

- producer-v3-kafka/src/main/java/com/datastax/cassandra/cdc/producer/Agent.java
- producer-v3-kafka/src/test/java/com/datastax/cdc/producer/KafkaProducerV3Tests.java
- producer-v3-pulsar/src/main/java/com/datastax/cassandra/cdc/producer/Agent.java
- producer-v3-pulsar/src/test/java/com/datastax/cassandra/cdc/producer/PulsarGenericSchemaTests.java
- producer-v4-kafka/src/main/java/com/datastax/cassandra/cdc/producer/Agent.java
- producer-v4-kafka/src/test/java/com/datastax/cdc/producer/KafkaProducerV4Tests.java
- producer-v4-pulsar/src/main/java/com/datastax/cassandra/cdc/producer/Agent.java
- producer-v4-pulsar/src/test/java/com/datastax/cassandra/cdc/producer/PulsarGenericSchemaTests.java
- producer/src/main/java/com/datastax/cassandra/cdc/producer/ProducerConfig.java
- producer/src/test/java/com/datastax/cassandra/cdc/producer/AgentParametersTest.java
- source-pulsar/src/main/java/com/datastax/oss/pulsar/source/CassandraSource.java
- source-pulsar/src/test/java/com/datastax/oss/pulsar/source/PulsarCassandraSourceTests.java
- Change Source id for Pulsar IO  to "cassandra-source"
- Add support for configuring the Producer using a Map<String, Object> in order to allow a better integration with the configuration in Astra DB
> Add ProducerConfiguration reader from Map<String,Object> and change Source ID  to cassandra-source

- connector-luna/build.gradle
- connector-pulsar/build.gradle
- gradle.properties
Running Sonatype IQ server scan against pulsar-connector.nar and luna-connector.nar shows up some dependencies with CVE. See the report: [lunastreaming-ci-Release-20220117-142433.pdf](https://github.com/datastax/cdc-apache-cassandra/files/7882669/lunastreaming-ci-Release-20220117-142433.pdf)
Forced transitive dependencies version:
* logback 1.2.9
* jackson Databind 2.12.6
* jnr 3.1.15
* netty 4.1.72.Final
* nettyTcNative 2.0.46.Final
* commonCompress 1.21
* gson 2.8.9
This affects the connector for Luna Streaming 2.7 and Luna Streaming/Pulsar 2.8
> [pulsar connectors] Upgrade dependencies to get rid of multiple CVEs

- .github/workflows/publish.yml
- .gitignore
- docs/README.adoc
- docs/antora-template.yml
- docs/build.gradle
Generate the docs/antora.yml config from a template file using a gradle task to update the project version.
> Generate docs with the project version

- connector/build.gradle
Fix #67
Connector is using `com.datastax.oss:java-driver-core-shaded` but it is not needed since the non-shaded version is already imported by another dependency
> [pulsar connector] Do not use DS driver core shaded

- agent/src/main/java/com/datastax/oss/cdc/agent/AbstractPulsarMutationSender.java
- commons/src/main/java/com/datastax/oss/cdc/NativeSchemaWrapper.java
- connector/src/main/java/com/datastax/oss/cdc/CassandraSourceConnectorConfig.java
- connector/src/main/java/com/datastax/oss/pulsar/source/CassandraSource.java
- connector/src/main/java/com/datastax/oss/pulsar/source/converters/AbstractGenericConverter.java
- connector/src/main/java/com/datastax/oss/pulsar/source/converters/AbstractNativeConverter.java
- connector/src/main/java/com/datastax/oss/pulsar/source/converters/NativeAvroConverter.java
- connector/src/main/java/com/datastax/oss/pulsar/source/converters/NativeJsonConverter.java
- connector/src/test/java/com/datastax/oss/cdc/CassandraSourceConnectorConfigTest.java
- connector/src/test/java/com/datastax/oss/pulsar/source/AvroKeyValueCassandraSourceTests.java
- connector/src/test/java/com/datastax/oss/pulsar/source/JsonKeyValueCassandraSourceTests.java
- connector/src/test/java/com/datastax/oss/pulsar/source/JsonOnlyCassandraSourceTests.java
- connector/src/test/java/com/datastax/oss/pulsar/source/PulsarCassandraSourceTests.java
- testcontainers/src/main/java/com/datastax/oss/cdc/DataSpec.java
This PR introduces two new format for C* source ([issue](https://github.com/datastax/cdc-apache-cassandra/issues/74)):
* kev-value-json: Similar to the existing AVRO option, the schema of the Pulsar record will be KEY_SCHEMA (key & value are SEPARATED JSON)  
* json: This option format the record as JSON only, so all fields in the payload (whether key or value fields) are top level fields in the value:
```
{
"key1" : "...",
"key2": "...".
...,
"field1" : "...",
"field2" : "...".
...
}
```
the record will have the key part encoded as will as an escaped json string.
To handle delete mutations for JSON only format, the data topic will receive an empty JSON payload '{}' - pulsar doesn't allow null payloads.
> Add JSON support for Cassandra source

- .github/workflows/ci.yaml
Currently the master branch doesn't compile due to license errors.
```
> License violations were found: /home/jenkins/workspace/Connectors/CDC_Push_Snapshot/connector/src/main/java/com/datastax/oss/pulsar/source/converters/NativeJsonConverter.java,/home/jenkins/workspace/Connectors/CDC_Push_Snapshot/connector/src/main/java/com/datastax/oss/pulsar/source/converters/AbstractNativeConverter.java}
```
The CI doesn't intercept the error since all the gradle command are just `test` and the license check doesn't depend on that phase.
> [ci] Add complete build on CI to ensure all checks pass

- gradle.properties
`jackson-databind`  2.12.6.1 is vulnerable to [CVE-2022-42003](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-42003)
* Upgrade to 2.12.7.1
there's no strong reason to bump to 2.13.x so it's more conservative to remain on 2.12.x
> Upgrade jackson to 2.12.7.1

- gradle.properties
Updating artifactory URL - using this PR mainly to verify CI will work with the new URLs. Previous PRs checks failed with:
```
* What went wrong:
Execution failed for task ':agent-dse4:compileJava'.
> Could not resolve all files for configuration ':agent-dse4:compileClasspath'.
> Could not resolve com.datastax.dse:dse-db:6.8.23.
Required by:
project :agent-dse4
> Could not resolve com.datastax.dse:dse-db:6.8.23.
> Could not get resource 'https://repo.datastax.com/artifactory/dse/com/datastax/dse/dse-db/6.8.23/dse-db-6.8.23.pom'.
> Could not GET 'https://repo.datastax.com/artifactory/dse/com/datastax/dse/dse-db/6.8.23/dse-db-6.8.23.pom'. Received status code 401 from server: Unauthorized
> Could not resolve com.datastax.dse:dse-db:6.8.23.
Deprecated Gradle features were used in this build, …
```
> Update artifactory extraRepoUrl to use datastax-releases-local

- commons/src/main/java/com/datastax/oss/cdc/NativeSchemaWrapper.java
Refrain from using the `SchemaInfoImpl` import to build schema info object. While testing with LS, the following error would manifest specifically when using `json` only output format:
```
...
Caused by: java.lang.ClassCastException: class org.apache.pulsar.client.impl.schema.SchemaInfoImpl cannot be cast to cl │
│     at org.apache.pulsar.common.protocol.schema.SchemaHash.of(SchemaHash.java:52) ~[com.datastax.oss-pulsar-common-2.10 │
``` 
I tested this patch by building a nar file locally and use it with k8s hosted LS image.
> Use SchemaInfo API to build SchemaInfo objects

- agent-dse4/src/main/java/com/datastax/oss/cdc/agent/PulsarMutationSender.java
- cdc-backfill-client/README.md
- cdc-backfill-client/build.gradle
- cdc-backfill-client/gradle.properties
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/BackFillSettings.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/BackfillCLI.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/CassandraToPulsarMigrator.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/ClusterInfo.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/Credentials.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/ExitStatus.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/ExportSettings.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/ExportedColumn.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/ExportedTable.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/HostAndPortConverter.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/PulsarImporter.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/TableExportReport.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/TableExporter.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/TableProcessor.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/VersionProvider.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/util/ConnectorUtils.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/util/LoggingUtils.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/util/ModelUtils.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/util/SessionUtils.java
- cdc-backfill-client/src/main/java/com/datastax/oss/cdc/backfill/util/TableUtils.java
- cdc-backfill-client/src/main/resources/logback-cdc-backfill.xml
- cdc-backfill-client/src/main/resources/logback-dsbulk-embedded.xml
- gradle.properties
- settings.gradle
Initial skeleton for the CDC backfill CLI tool:
* CLI take dependency on DSBulk to export the data to desk and start a CVS connector for the
* This PR shows the end to end skeleton to get early feedback on the project skeleton and over all approach, unit tests/refactoring are coming up.
* Will local DSE and Pulsar, the following command should run e2e:
```
./gradlew cdc-backfill-client:assemble
java  -jar cdc-backfill-client/build/libs/cdc-backfill-client-2.2.3-all.jar backfill --data-dir=target/export --export-host=127.0.0.1:9042 --export-username=cassandra --export-password=cassandra --keyspace ks1 --table sample1
```
* Lots of settings are imported as is from DSBulk - will reduce those to the bare minimum
* Parts of the codes assumes multiple table migrations concurrently, this could …
> Implement cdc backfill skeleton

- connector/build.gradle
- gradle.properties
* move to jackson BOM 2.13.4 to avoid CVEs
* `messaging-connectors-commons` depends on `kafka-clients` for the config. 2.5.1 contains CVE-2023-25194.
Upgrade to 3.4.0
> [security] Upgrade jackson and kafka-clients

- .github/workflows/backfill-ci.yaml
- .github/workflows/ci.yaml
Update the pulsar ci test matrix:
- `datastax/lunastreaming:2.10_2.4`
- `apachepulsar/pulsar:2.10.3`
- `apachepulsar/pulsar:2.11.0`
Please note that previous, the test matrix was not taking affect and all tests ran against `datastax/lunastreaming:2.8.0_1.1.42` due to misconfiguration in the CI files.
> Update the pulsar ci test matrix

- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/importer/PulsarImporter.java
- backfill-cli/src/test/java/com/datastax/oss/cdc/backfill/PulsarImporterTest.java
Limit the number of inflight pulsar mutations to 1000 (hard coded for now) inspired by how the agent doesn't (independent from the blocking send capabilities in the pulsar client)
> Limit the number of inflight pulsar mutations

- backfill-cli/build.gradle
- backfill-cli/gradle.properties
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/admin/BackfillCommand.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/admin/CommandFactory.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/dsbulk/BackfillBulkLoader.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/dsbulk/BackfillBulkLoaderCommandLineParser.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/dsbulk/BackfillConfigUtil.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/dsbulk/BackfillGlobalHelpRequestException.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/dsbulk/BackfillParsedCommandLine.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/dsbulk/BackfillUnloadWorkflow.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/dsbulk/LogSettings.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/exporter/TableExporter.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/importer/PulsarImporter.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/util/ConnectorUtils.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/util/LoggingUtils.java
- backfill-cli/src/main/resources/META-INF/MANIFEST.MF
- backfill-cli/src/main/resources/META-INF/services/command_factory.yml
- backfill-cli/src/main/resources/driver-reference.conf
- backfill-cli/src/main/resources/logback.xml
- backfill-cli/src/test/java/com/datastax/oss/cdc/backfill/PulsarImporterTest.java
- build.gradle
This patch adds initial support for running `backfill-cli` as a pulsar admin extension. I tested the happy path locally using the LS2.10_3 tarball:
```
bin/pulsar-admin cassandra-cdc backfill --data-dir target/export --export-host 127.0.0.1:9042 --export-username cassandra --export-password cassandra --keyspace ks1 --table sample4
```
in the `client.conf` I added the following line:
```
customCommandFactories=cassandra-cdc
```
**Implementation notes:** 
* Added few DSBulk workarounds to make it class loader aware, and to have it run with a log4j log implementation. For more regarding the long term solution, please check https://github.com/datastax/dsbulk/issues/465 & https://github.com/datastax/dsbulk/issues/466
* Added a nar file task to be used as a pulsar admin extention
* Added basic …
> Add cassandra-cdc backfill command as a Pulsar Admin Extension

- backfill-cli/build.gradle
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/BackfillCLI.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/BackfillSettings.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/admin/BackfillCommand.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/exporter/ExportSettings.java
- backfill-cli/src/test/java/com/datastax/oss/cdc/backfill/e2e/BackfillCLIE2ETests.java
This patch:
* Read pulsar client related configs (broker url, tls, etc) from the client conf
* Adds the exhaustive list of options available in the backfill CLI to the pulsar admin extension variant
* Handle list array option `--export-dsbulk-option`
* Improves error messages returned from picocli to pulsar admin
> Parse extra backfill configs from client.conf and CLI

- backfill-cli/build.gradle
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/admin/BackfillCommand.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/factory/CodecFactory.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/importer/PulsarImporter.java
- backfill-cli/src/test/java/com/datastax/oss/cdc/backfill/PulsarImporterTest.java
- backfill-cli/src/test/java/com/datastax/oss/cdc/backfill/e2e/BackfillCLIE2ETests.java
- backfill-cli/src/test/resources/client.conf
- backfill-cli/src/test/resources/sample-002.csv
The patch updates the Cassandra CDC backfill CLI to use the Pulsar Admin CLI Extension for e2e testing. The motivation:
1. The "extension" is the recommend way to run backfilling. 
2. It already exercise the code path that was previously tested if someone where to run the jar directly with the exception of a thin wrapper for the CLI entry point. 
If necessary, we could enable tests on both the JAR and the NAR artifacts but this seems like an overkill for the time being. 
Update: I'll fall back to testing with the JAR when CLI ext is not enabled.
> Use the backfill pulsar admin ext for e2e tests

- agent-c4/build.gradle
- agent-c4/src/main/java/com/datastax/oss/cdc/agent/PulsarMutationSender.java
- agent-dse4/src/main/java/com/datastax/oss/cdc/agent/PulsarMutationSender.java
- backfill-cli/build.gradle
Remove dse-db dependency from backfill-cli so external users can build (#125 )
> Remove dse-db dependency from backfill-cli

- gradle.properties
Update the C* OSS Java Driver version to 2.15.0 to get access to some advanced settings, like:
```
datastax-java-driver.advanced.address-translator.advertised-hostname
```
> Update the oss java driver to 2.15

- .github/workflows/backfill-ci.yaml
- .github/workflows/ci.yaml
- README.md
- settings.gradle
This patch avoids dse build error for external users. I verified the build from an external machine.
> Exclude agent-dse4 build artifacts by default

- backfill-cli/build.gradle
Add Conscrypt security provided as recommend by pulsar when using SSL. It also avoids this warning:
```
16:53:26.782 WARN  Conscrypt isn't available. Using JDK default security provider.
java.lang.ClassNotFoundException: org.conscrypt.Conscrypt
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:315)
at org.apache.pulsar.common.util.SecurityUtility.loadConscryptProvider(SecurityUtility.java:124)
at org.apache.pulsar.common.util.SecurityUtility.<clinit>(SecurityUtility.java:81)
at …
```
> Add Conscrypt security provider

- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/admin/BackfillCommand.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/exporter/ExportSettings.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/exporter/TableExporter.java
The `--export-max-records` maps to DSBulk -maxRecords flag which is currently not working as expected. Check https://github.com/datastax/dsbulk/issues/470  
For bow, the backfill tool will drop this flag, and will be restored once we sort out the maxRecords. Please note the all DSBulk settings can be still be passed via the `--export-dsbulk-option`
> Drop the --export-max-records flag

- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/importer/PulsarImporter.java
- backfill-cli/src/test/java/com/datastax/oss/cdc/backfill/PulsarImporterTest.java
Close mutation sender after completing import. This will make sure that the CLI can be invoked when the container shell is not recycled.
> Close mutation sender after completing import

- agent/src/main/java/com/datastax/oss/cdc/agent/AbstractPulsarMutationSender.java
- backfill-cli/src/main/java/com/datastax/oss/cdc/backfill/importer/PulsarImporter.java
- backfill-cli/src/test/java/com/datastax/oss/cdc/backfill/PulsarImporterTest.java
The connector sends a `replication_latency` e2e metric based on the `WRITETIME` property that originates from a mutation on the commit log. For backfilled items, the writetime is not indicative of latency as those are historical items and will lead to skewed metric. The connector sends the metric [only if ](https://github.com/datastax/cdc-apache-cassandra/blob/2c59270d237039cbd649c306fbd99cdb6963f60c/connector/src/main/java/com/datastax/oss/pulsar/source/CassandraSource.java#L523)the property exists.
Notes:
* Changing the tsMicro to `Long` or `Optional<Long>` would require changing the agent3/4/dse implementations. It is also unnecessary because typical a timestamp should be available but I'm making an exception for backfilled items
* `AbstractPulsarMutationSender` is not unit test …
> Disable the replication_latency metric for backfilled items

- agent/build.gradle
- agent/src/main/java/com/datastax/oss/cdc/agent/AbstractDirectoryWatcher.java
- agent/src/main/java/com/datastax/oss/cdc/agent/CommitLogProcessor.java
- agent/src/main/java/com/datastax/oss/cdc/agent/CommitLogReaderService.java
- agent/src/test/java/com/datastax/oss/cdc/agent/AbstractDirectoryWatcherTest.java
This patch:
* Ensures `WatchKey#reset()` is called in the case of event handling exception
* Register to and log `java.nio.file.StandardWatchEventKinds.OVERFLOW` if any
* Adds extra logging
> Improve WatchService error handling & logging

- agent/src/main/java/com/datastax/oss/cdc/agent/CommitLogReaderService.java
- agent/src/test/java/com/datastax/oss/cdc/agent/CommitLogReaderServiceTest.java
This patch solves a problem on the agent when pulsar is temporarily unavailable and then recovers, task with partial failures could hand forever. Here is a sample timeline: 
**[T1]** Pulsar endpoint is not reachable due to a network problem
**[T2]** A CDC enabled table continues to receive mutations. All mutations are sent to the `cdc_raw` for async processing
**[T3]** Agent picks up the `*.idx` files form the `cdc_raw` and submits to the `pendingTasks` queue for execution. Although there is logical 1:1 mapping between a `Task` and a `segment` (represented by a pair of `*.idx` and `*.log` files in the commit log dir, the segment file is mutable. With each segment mutation, a new task is submitted for processing.   
**[T4]** Task starts, it will read the log files and starts sending …
> Release all semaphore permits when the current task instance is to be retried

- agent-dse4/build.gradle
- agent-dse4/src/main/java/com/datastax/oss/cdc/agent/Agent.java
Add agent version to the log upon start for troubleshooting. Check `Implementation-Version` on https://docs.oracle.com/javase/tutorial/deployment/jar/packageman.html
Tested locally:
```
INFO  [main] 2023-05-10 14:54:40,672  Agent.java:61 - Starting CDC agent v2.2.8, cdc_raw_directory=/private/var/lib/cassandra/cdc_raw
```
> Log agent version on startup

- docs/playbooks/site-local-cdc-cassandra.yaml
- docs/playbooks/site-publish-cdc-cassandra.yaml
**JIRA:** https://datastax.jira.com/browse/DOC-3853
This change updates/adds the `support_url` attribute with the correct link to the DataStax Support website.
> DOC-3853: Update/add support_url attribute

- docs/docs-src/core/antora-cdc-cassandra.yml
- docs/docs-src/core/modules/ROOT/examples/java-start.sh
- docs/docs-src/core/modules/ROOT/pages/backfill-cli.adoc
Add a `version` asciidoc attribute to reference the current cdc release version in docs.
Reference it with `{version}`.
Note that you will need to include the `,subs="attributes+"` to render the variable in code sample blocks, as below.
```
Java standalone::
+
--
[source,shell,subs="attributes+"]
----
include::example$java-start.sh[]
----
--
```
Coppi build: https://coppi.aws.dsinternal.org/en/latest-version-var/docs/2.2.9/backfill-cli.html
> version-resolve

- backfill-cli/gradle.properties
- gradle.properties
At the time https://github.com/datastax/cdc-apache-cassandra/pull/144 was implemented, pulsar client 2.10.4 was not released. This patch is a follow up to use the recommended version. Please note that 2.11 is not possible to use atm because it required java 17 CDC need to compile with java 11,
> Upgrade pulsar client to 3.0.0

- gradle.properties
Avro 1.11.3 contains critical 9.3/10 level RCE vulnerability in Avro Java SDK <1.11.4, [CVE-2024-47561](https://github.com/advisories/GHSA-r7pg-v2c8-mfg3)>
> Upgrade Avro to 1.11.4 to address CVE-2024-47561

- build.gradle
Added the org.ajoberstar.grgit plugin to build.gradle to resolve dependency issues with com.gorylenko.gradle-git-properties. This ensures that the required grgit-core dependency can be correctly fetched during the Gradle build process.
> fix: add org.ajoberstar.grgit plugin to build.gradle to resolve dependency issue

- .github/workflows/ci.yaml
- connector/src/main/java/com/datastax/oss/pulsar/source/ConverterAndQuery.java
- connector/src/test/java/com/datastax/oss/pulsar/source/PulsarCassandraSourceTests.java
- gradle.properties
**What does this patch do**
This patch fixes an issue when primary keys contain clustering key and a user issues a partition delete. 
Take the following schema as an example:
```
CREATE TABLE ks1.test (
pk text,
c1 text,
val text,
PRIMARY KEY (pk, c1)
```
If a user issues a `DELETE FROM test WHERE pk=<pk>`, the agent would push an event with pk only (c1 will not exist) and then the connector will perform the read back using a faulty query (missing a projection clause) evident from debug logs:
```
[pool-6-thread-1] DEBUG com.datastax.oss.cdc.CassandraClient - SELECT FROM ks1.test WHERE pk=?
```
That will cause the C* driver throw an exception logged into the pulsar function (i.e. the connector)
```
com.datastax.oss.driver.api.core.servererrors.SyntaxError: line 1:7 no viable alternative at …
```
> [connector][fix] Properly handle projection clause for partition deletes
